version: 0.2
# Codebuild用設定ファイル
phases:
  pre_build:
    commands:
      - aws --version
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region {region} | docker login --username AWS --password-stdin {Account ID}.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -f ./Dockerfile -t {ECR name}:latest .
      - docker tag {ECR name}:latest {Account ID}.dkr.ecr.ap-northeast-1.amazonaws.com/{ECR name}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push {Account ID}.dkr.ecr.ap-northeast-1.amazonaws.com/{ECR name}:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' {ECR name} {Account ID}.dkr.ecr.ap-northeast-1.amazonaws.com/{ECR name}:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
